import React,{createContext,useContext,useEffect,useState} from 'react';
import ReactDOM from 'react-dom/client';
import axios from 'axios';
import {BrowserRouter,Routes,Route,Link,NavLink,Navigate,useNavigate} from 'react-router-dom';
import './styles.css';

const api=axios.create({baseURL:import.meta.env.VITE_API_URL||'http://localhost:8000/api',timeout:120000});
api.interceptors.request.use(c=>{const t=localStorage.getItem('token');if(t)c.headers.Authorization=`Bearer ${t}`;return c});
const err=e=>e.response?.data?.detail||e.message;
const Auth=createContext();
function AuthProvider({children}){const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('user')||'null'));
 const save=d=>{localStorage.setItem('token',d.access_token);localStorage.setItem('user',JSON.stringify(d.user));setUser(d.user)};
 const logout=()=>{localStorage.clear();setUser(null)}; return <Auth.Provider value={{user,save,logout}}>{children}</Auth.Provider>}
function Guard({children}){return useContext(Auth).user?children:<Navigate to="/login"/>}
function Landing(){return <main className="landing"><nav><b>HybridDocs AI</b><span><Link to="/login">Sign in</Link><Link className="btn" to="/register">Create account</Link></span></nav><section><div><small>HYBRID RETRIEVAL + CITATIONS</small><h1>Ask your documents. Inspect every source.</h1><p>Upload PDF, DOCX, TXT, Markdown or HTML. Dense search, BM25, RRF and reranking produce grounded answers.</p><Link className="btn" to="/register">Start building</Link></div><aside><strong>What does AUTH-104 mean?</strong><p>It means the access token expired or has an invalid signature. Request a new token first. [1]</p><em>[1] engineering_runbook.txt</em></aside></section></main>}
function AuthPage({register=false}){const [f,setF]=useState({name:'',email:'',password:''});const [error,setError]=useState('');const {save}=useContext(Auth);const nav=useNavigate();
 async function submit(e){e.preventDefault();setError('');try{const url=register?'/auth/register':'/auth/login';const body=register?{full_name:f.name,email:f.email,password:f.password}:{email:f.email,password:f.password};const {data}=await api.post(url,body);save(data);nav('/app')}catch(x){setError(err(x))}}
 return <div className="auth"><form onSubmit={submit}><Link to="/">← Home</Link><h1>{register?'Create workspace':'Welcome back'}</h1>{register&&<input placeholder="Full name" required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/>}<input type="email" placeholder="Email" required value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input type="password" minLength="8" placeholder="Password" required value={f.password} onChange={e=>setF({...f,password:e.target.value})}/>{error&&<div className="error">{error}</div>}<button className="btn">{register?'Create account':'Sign in'}</button><p>{register?'Already registered?':'New here?'} <Link to={register?'/login':'/register'}>{register?'Sign in':'Create account'}</Link></p></form></div>}
function Layout(){const {user,logout}=useContext(Auth);return <div className="shell"><aside><h2>HybridDocs</h2><NavLink end to="/app">Overview</NavLink><NavLink to="/app/documents">Documents</NavLink><NavLink to="/app/chat">Ask documents</NavLink><footer><b>{user.full_name}</b><small>{user.email}</small><button onClick={logout}>Sign out</button></footer></aside><div className="content"><Routes><Route index element={<Dashboard/>}/><Route path="documents" element={<Documents/>}/><Route path="chat" element={<Chat/>}/></Routes></div></div>}
function Dashboard(){const [s,setS]=useState(null);useEffect(()=>{api.get('/stats').then(r=>setS(r.data))},[]);return <Page title="Overview" sub="Your private knowledge workspace."><div className="stats">{[['documents','Documents'],['indexed_documents','Indexed'],['chunks','Chunks'],['conversations','Chats']].map(([k,l])=><article key={k}><span>{l}</span><b>{s?.[k]??'—'}</b></article>)}</div><div className="panel"><h2>How it works</h2><ol><li>Upload internal documents.</li><li>The backend chunks and embeds them.</li><li>Dense and BM25 results are fused and reranked.</li><li>Groq answers only from retrieved context with citations.</li></ol></div></Page>}
function Page({title,sub,children}){return <main className="page"><header><small>HYBRIDDOCS AI</small><h1>{title}</h1><p>{sub}</p></header>{children}</main>}
function Documents(){const [docs,setDocs]=useState([]),[file,setFile]=useState(),[strategy,setStrategy]=useState('recursive'),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);const load=()=>api.get('/documents').then(r=>setDocs(r.data));useEffect(load,[]);
 async function upload(e){e.preventDefault();setBusy(true);setMsg('');const b=new FormData();b.append('file',file);b.append('chunking_strategy',strategy);try{const {data}=await api.post('/documents/upload',b);setMsg(`${data.original_name}: ${data.chunk_count} chunks`);load()}catch(x){setMsg(err(x))}finally{setBusy(false)}}
 async function del(d){if(confirm(`Delete ${d.original_name}?`)){await api.delete(`/documents/${d.id}`);load()}}
 return <Page title="Documents" sub="Upload and manage indexed sources."><form className="upload" onSubmit={upload}><input type="file" accept=".pdf,.docx,.txt,.md,.html,.htm" required onChange={e=>setFile(e.target.files[0])}/><select value={strategy} onChange={e=>setStrategy(e.target.value)}><option value="recursive">Recursive</option><option value="fixed">Fixed</option><option value="semantic">Semantic</option></select><button className="btn" disabled={busy}>{busy?'Indexing…':'Upload & index'}</button></form>{msg&&<div className="notice">{msg}</div>}<div className="panel list">{docs.length?docs.map(d=><article key={d.id}><div><b>{d.original_name}</b><small>{d.file_type.toUpperCase()} · {d.chunk_count} chunks · {d.chunking_strategy}</small>{d.error_message&&<em>{d.error_message}</em>}</div><span className={d.status}>{d.status}</span><button onClick={()=>del(d)}>Delete</button></article>):<p>No documents yet.</p>}</div></Page>}
function Chat(){const [q,setQ]=useState(''),[mode,setMode]=useState('hybrid'),[cid,setCid]=useState(null),[messages,setMessages]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function ask(e){e.preventDefault();if(!q.trim())return;const question=q;setQ('');setMessages(x=>[...x,{role:'user',content:question}]);setBusy(true);setError('');try{const {data}=await api.post('/chat/ask',{question,conversation_id:cid,retrieval_mode:mode,top_k:5});setCid(data.conversation_id);setMessages(x=>[...x,{role:'assistant',...data}])}catch(x){setError(err(x))}finally{setBusy(false)}}
 return <div className="chat"><header><div><small>GROUNDED CHAT</small><h1>Ask your knowledge base</h1></div><select value={mode} onChange={e=>setMode(e.target.value)}><option value="hybrid">Hybrid</option><option value="dense">Dense</option><option value="bm25">BM25</option></select></header><div className="messages">{!messages.length&&<div className="empty"><h2>Ask a precise question</h2><p>Every answer shows its sources and retrieval scores.</p></div>}{messages.map((m,i)=><article className={`message ${m.role}`} key={i}><b>{m.role==='user'?'You':'HybridDocs'}</b><div><p>{m.content||m.answer}</p>{m.confidence&&<div className="confidence">Confidence {Math.round(m.confidence.composite*100)}%</div>}{m.sources?.map(s=><section className="source" key={s.chunk_id}><strong>[{s.citation}] {s.filename}</strong><small>{s.page_number?`Page ${s.page_number}`:''} {s.section_heading||''}</small><p>{s.excerpt}</p></section>)}{m.retrieved_chunks&&<details><summary>Retrieval inspector</summary>{m.retrieved_chunks.map(h=><div className="hit" key={h.chunk_id}><b>{h.filename}</b><span>Dense #{h.dense_rank||'—'} · BM25 #{h.sparse_rank||'—'} · Final {h.final_score.toFixed(3)}</span></div>)}</details>}</div></article>)}{busy&&<p>Retrieving and checking sources…</p>}{error&&<div className="error">{error}</div>}</div><form className="composer" onSubmit={ask}><textarea value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask about your documents…"/><button className="btn" disabled={busy}>Ask</button></form></div>}
function App(){return <Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<AuthPage/>}/><Route path="/register" element={<AuthPage register/>}/><Route path="/app/*" element={<Guard><Layout/></Guard>}/><Route path="*" element={<Navigate to="/"/>}/></Routes>}
ReactDOM.createRoot(document.getElementById('root')).render(<BrowserRouter><AuthProvider><App/></AuthProvider></BrowserRouter>);
